# opencode
openai.baseUrl=https://opencode.ai/zen/v1
# opencode 提供很多免费模型 https://opencode.ai/docs/zh-cn/zen#%E5%AE%9A%E4%BB%B7
openai.model=minimax-m2.5-free
openai.model=qwen3.6-plus-free
openai.apiKey=sk-xkxovFyYXQe2mya9ZwLhizLj6BWKMNQp1p1Ktc9oxczBTjzHCF05Xomt4o8AfgWY
###

# LM Studio
openai.baseUrl=http://localhost:1234/v1
openai.apiKey=
openai.model=qwen3.5-2b-claude-4.6-opus-reasoning-distilled
openai.model=qwen/qwen3.5-2b
openai.model=qwen3.5-0.8b-claude-4.6-opus-reasoning-distilled
openai.model=minicpm4-0.5b-qat-int4
openai.model=qwen3.5-0.8b


openai.maxRetries=0
openai.proxy=http://127.0.0.1:8888
openai.proxy.ca=/data/app/charles/charles.pem